// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA_ixRVOFmDeuUGskPOPfoFFgEqWDDtio',
    appId: '1:457041441165:web:33d182e8f572c6f2c9cdc4',
    messagingSenderId: '457041441165',
    projectId: 'tempgeoloc-38a01',
    authDomain: 'tempgeoloc-38a01.firebaseapp.com',
    databaseURL: 'https://tempgeoloc-38a01-default-rtdb.firebaseio.com',
    storageBucket: 'tempgeoloc-38a01.firebasestorage.app',
    measurementId: 'G-05XSEQTH25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxt-uj4ZbUwx_YYKnEGatXTiSlMs3LNAQ',
    appId: '1:457041441165:android:df3ade1a39a6b6bfc9cdc4',
    messagingSenderId: '457041441165',
    projectId: 'tempgeoloc-38a01',
    databaseURL: 'https://tempgeoloc-38a01-default-rtdb.firebaseio.com',
    storageBucket: 'tempgeoloc-38a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc_qdtm4iW0SR4WC3CZETok-BqT3pFAfM',
    appId: '1:457041441165:ios:cd907eebc2eae9b6c9cdc4',
    messagingSenderId: '457041441165',
    projectId: 'tempgeoloc-38a01',
    databaseURL: 'https://tempgeoloc-38a01-default-rtdb.firebaseio.com',
    storageBucket: 'tempgeoloc-38a01.firebasestorage.app',
    androidClientId: '457041441165-vvfp8ih7uc4e1qe8g68js637q50lsmeq.apps.googleusercontent.com',
    iosClientId: '457041441165-6oabs3mg8ssoniuo5013gg5rei95ifg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveillanceuser',
  );
}
